### ISSUE TITLE
Url-loader is called twice and prevents loading of svg logo

### ISSUE THREAD

**Issue by dvvanessastoiber** [phovea/phovea_ui#111]
* Release number or git hash: e7df1bc3be93ed863e0e7a938b91470d457dd0c6
* Web browser version and OS: Chrome 81, Linux
* Environment (local or deployed): local

### Steps to reproduce

1. Open taco or gapminder

### Observed behavior
* SVG Logo is not displayed correctly
* due to this line, the `url-loader` is called twice, which causes the problem
```
import * as caleydoLogo from 'url-loader!./assets/caleydo_c.svg';
```

### Expected behavior
* Logo should be shown correctly

**Comment by anita-steiner** [comment]
should be fixed with the new webpack configs
