### ISSUE TITLE
Check 'lastdeployment' just on the fly

### ISSUE THREAD

**Issue by sgratzl** [phovea/phovea_ui#6]
avoids the initial ajax request

**Comment by sgratzl** [comment]
+ is not valid anymore on the server side

**Comment by thinkh** [comment]
Done.

![lastdeployment-on-demand](https://cloud.githubusercontent.com/assets/5851088/23129214/0fbdaf3a-f782-11e6-8180-690782200b38.gif)

**Comment by sgratzl** [comment]
have you checked the server output, too?

**Comment by thinkh** [comment]
what do you mean?

**Comment by sgratzl** [comment]
I mean there is no "package.json" file anymore in the production server

**Comment by thinkh** [comment]
I think thats a new issue. :)
