### ISSUE TITLE
Prompt-Dialog not submitting on OK click

### ISSUE THREAD

**Issue by dvmichaelpuehringer** [phovea/phovea_ui#66]
Currently, the `prompt`-dialog does not perform any action (as the `onSubmit` is not utilized) when clicking on the primary button. 
The content of the form should be returned on `OK` click, and null should be returned if the dialog was hidden.

**Comment by thinkh** [comment]
Example from provenance story editor:

![clue-wrong-prompt-dialog](https://user-images.githubusercontent.com/5851088/64161564-25dc4e80-ce3e-11e9-8be6-fb3601a36aeb.gif)
